# Site settings
title: Katarzyna Przybyła Portfolio
email: kasiakiero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Katarzyna Przybyła
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://katarzynaprzybyla.pl" # the base hostname & protocol for your site
img_url: /assets/img/
title_image: title_image.jpg # najlepiej coś w rozmiarze 500x150px
google_analytics: G-YWZ4B05RC0

# twitter_username: jekyllrb
github_username:  kasiakiero
facebook_username: kasiakiero

# collections:
  # posts:
    # output: true
permalink: /projects/:title/

# Build settings
markdown: kramdown
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag

#https://jekyllrb.com/docs/configuration/options/
exclude: [
  "Makefile",
  ".sass-cache/",
  ".jekyll-cache/",
  "gemfiles/",
  "Gemfile",
  "Gemfile.lock",
  "node_modules/",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/"
]