# Site settings
title: Blog Kasi Kiero
email: kasiakiero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Moja strona domowa, będą tu fajne rzeczy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kasiakiero.github.io/" # the base hostname & protocol for your site
img_url: /assets/img/
title_image: title_image.jpg # najlepiej coś w rozmiarze 500x150px

# twitter_username: jekyllrb
github_username:  kasiakiero
facebook_username: kasiakiero


# Build settings
markdown: kramdown
permalink: pretty
